export const Whitam = 'black';
export const Wprimer = '#039BE5';
export const Wputih = '#ffffff';
export const WbiruC = '#03A9F4';
export const Wabu = '#CFD8DC';
export const Wabu1 = '#B0BEC5';
export const Wabu2 = '#FAFAFA';
// export const WbiruC = '#039BE5';
// export const WbiruC = '#039BE5';
